window.agenticIncidentOpsData = {
  product: 'Agentic Incident Ops',
  version: '0.3.0',
  prod: 83,
  deadline: '2026-06-29 11:45 PM PDT',
  track: 'UiPath Maestro Case',
  tagline: 'Governed agents for auditable production incident response.',
  metrics: [
    { label: 'Workflow', value: '7 stages', tone: 'blue' },
    { label: 'Human gates', value: '5', tone: 'red' },
    { label: 'Evidence', value: '9 packs', tone: 'green' },
    { label: 'Readiness', value: '83%', tone: 'amber' },
  ],
  caseSummary: {
    id: 'INC-2026-0529-API',
    service: 'Checkout API',
    severity: 'SEV-2',
    impact: '$18.6k at risk',
    current: 'Approval gate ready',
  },
  timeline: [
    { actor: 'Agent', title: 'Normalize incident intake', status: 'done', confidence: 72 },
    { actor: 'Robot/API', title: 'Collect evidence receipts', status: 'done', confidence: 81 },
    { actor: 'Coded Agent', title: 'Rank root-cause hypotheses', status: 'done', confidence: 88 },
    { actor: 'Human', title: 'Approve remediation gate', status: 'gate', confidence: 88 },
    { actor: 'Robot/API', title: 'Execute approved runbook', status: 'ready', confidence: 94 },
    { actor: 'Agent', title: 'Close with postmortem packet', status: 'ready', confidence: 96 },
  ],
  battlecard: [
    { label: 'Generic chatbot incident assistant', threat: 82, counter: 'UiPath controls approvals and execution receipts.' },
    { label: 'Monitoring vendor AI summary', threat: 78, counter: 'We orchestrate remediation, not only summarize signals.' },
    { label: 'Runbook automation script', threat: 74, counter: 'Maestro handles dynamic cases, humans, exceptions, and audit.' },
    { label: 'ITSM workflow plugin', threat: 69, counter: 'Agents reason across evidence and produce postmortem packets.' },
  ],
  evidence: [
    { name: 'Maestro case blueprint', state: 'ready', path: 'uipath/agentic_incident_ops.case_blueprint.json' },
    { name: 'Devpost packet', state: 'ready', path: 'docs/DEVPOST_SUBMISSION_PACKET.md' },
    { name: 'Video script', state: 'ready', path: 'docs/VIDEO_OUTLINE.md' },
    { name: 'Codex evidence', state: 'ready', path: 'evidence/codex-agent-usage.md' },
    { name: 'Readiness report', state: 'generating', path: 'evidence/generated/readiness_report.json' },
    { name: 'Live UiPath screenshots', state: 'pending', path: 'evidence/screenshots' },
  ],
  automations: [
    { name: 'V readiness validator', state: 'ready', command: 'v run cmd\\uipath_agenthack validate' },
    { name: 'V evidence pack', state: 'ready', command: 'v run cmd\\uipath_agenthack pack' },
    { name: 'Devpost draft fill', state: 'ready', command: 'node automation/devpost_fill_draft.mjs --save-draft' },
    { name: 'WAIBA visual QA', state: 'ready', command: 'DesignQA.AutoNestedEvaluate' },
  ],
  story: [
    'Agents recommend; Maestro governs.',
    'Humans approve risky production action.',
    'Robots and API Workflows execute deterministic runbooks.',
    'Every action leaves a receipt for audit and postmortem.',
  ],
};
